language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests && pylint --errors-only connectors.smugsync connectors.filesystem

notifications:
  slack: smugsync:vrkpzFAUm5ORKTcJaECpFEdL
